config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  resources :posts do
    resources :comments, :only => :create
  end

  resources :tags, :only => :show
  resources :users, :only => :show

  get '/sign_in', to: 'users#sign_in'
  post '/sign_in', to: 'users#sign_in!'
  get '/sign_up', to: 'users#sign_up'
  post '/sign_up', to: 'users#sign_up!'
  get '/sign_out', to: 'users#sign_out'

  # get "posts" => "posts#index"
  # get "posts/new" => "posts#new"
  # post "posts" => "posts#create"
  # get "posts/:id" => "posts#show"
  # get "posts/:id/edit" => "posts#edit"
  # put "posts/:id" => "posts#update"
  # delete "posts/:id" => "posts#destroy"
  #
  # get "comments/new" => "comments#new"
  # post "comments" => "comments#create"
  # get "comments/:id" => "comments#show"
  # get "comments/:id/edit" => "comments#edit"
  # put "comments/:id" => "comments#update"
  # delete "comments/:id" => "comments#destroy"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  def date
    return self.created_at.strftime("%b %d %y")
  end

  def time
    return self.created_at.strftime("%I %M %p")
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags

  def date
    return self.created_at.strftime("%b %d %y")
  end

  def time
    return self.created_at.strftime("%I %M %p")
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  validates :username, presence: true, uniqueness: true
  has_secure_password


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate
  before_filter :get_user

  def get_user
    if session[:user]
      @user = User.find(session[:user]["id"])
    end
  end
  
  private
  def authenticate
    if !session[:user]
      redirect_to "/sign_in"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @user = User.find(session[:user]["id"])
    @post = Post.find(params[:post_id])
    #@comment.save(comment_params.merge(post: @post))
    @comment = Comment.create!(comment_params.merge(post_id: @post.id, user_id: @user.id))

    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:text)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate, only: [:index]

  def index
    @posts = Post.all.order('created_at DESC')
    @tags = Tag.all
  end

  def show
    @user = current_user
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    #@user = User.find(session[:user]["id"])
    @post = current_user.posts.create!(post_params)
    if params[:tagtext] != ""
      @tag_arr = (params[:tagtext]).split
      @tag_arr.each do |tag|
        @tag = Tag.find_by(tagtext: tag)
        if @tag == nil
          @post.tags.create!(tagtext: tag)
        else
          #this literally took me an hour to find...
          @post.tags << @tag
        end
      end
    end

    redirect_to posts_path
  end

  def edit
    #@user = User.find(session[:user]["id"])
    @post = current_user.posts.find(params[:id])
    #if @user.id == @post.id

  end

  def update
    @post = current_user.posts.find(params[:id])
    @post.update(post_params)

    redirect_to post_path(@post)
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :text)
  end

  def current_user
    return User.find(session[:user]["id"])
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find(params[:id])
    @posts = @tag.posts
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate

  def sign_up
  end

  def sign_up!
    user = User.new(
      username: params[:username],
      password_digest: BCrypt::Password.create(params[:password])
    )
    if params[:password_confirmation] != params[:password]
      message = "Your passwords don't match!"
    elsif user.save
      message = "Your account has been created!"
    else
      message = "Your account couldn't be created. Did you enter a unique username and password?"
    end
    flash[:notice] = message
    redirect_to action: :sign_in
  end

  def sign_in
  end

  def sign_in!
    @user = User.find_by(username: params[:username])
    if !@user
      message = "This user doesn't exist!"
    elsif !BCrypt::Password.new(@user.password_digest).is_password?(params[:password])
      message = "Your password's wrong!"
    else
      message = "You're signed in, #{@user.username}!"
      cookies[:username] = {
      value: @user.username,
      expires: 100.years.from_now
      }
      session[:user] = @user
    end
    flash[:notice] = message
    redirect_to posts_path
  end

  def sign_out

    reset_session
    flash[:notice] = "You're signed out!"
    redirect_to posts_path
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scribble</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "scribble", root_path, {:class=>"navbar-brand" } %>
        <!-- <a class="navbar-brand" href="#">scribble</a> -->
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if session[:user] %>
            <li><%= link_to "#{@user.username}", user_path(@user) %></li>
            <li><%= link_to "new", new_post_path %></li>
            <li><%= link_to "signout", sign_out_path %></li>
          <% else %>
            <li><%= link_to "signup", sign_up_path %></li>
            <li><%= link_to "signin", sign_in_path %></li>
          <% end %>
      </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for [@post], :html => {:class => "form-horizontal"} do |f| %>
  <div class="form-group">
    <label class="col-sm-2 control-label"></label>
    <div class="col-sm-8">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label"></label>
    <div class="col-sm-8">
      <%= f.text_area :text, class: "form-control", :cols => "10", :rows => "10" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "create", class: "btn btn-default btn-primary"  %>
    </div>
  </div>
<% end  %>

app/views/posts/edit.html.erb
<%= render partial: "form" %>

app/views/posts/index.html.erb
<div id="alert" class="alert alert-info" role="alert"><%= flash[:notice]%></div>
<% @counter = 0 %>
<% @posts.each do |post| %>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-5">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= link_to "#{post.title}", post_path(post) %></h3>
      </div>
      <div class="panel-body">
        <p><%= post.text %></p>
        <div id="byline"><%= post.user.username %></div><div id="time"><%= post.date %> </div> <div id="time"> <%= post.time %></div>
        <h6><% (post.tags).each do |tag| %><span> <%= link_to "##{tag.tagtext}", tag_path(tag) %></span><% end %></h6>
      </div>

      <div class="well">
        <p>comments</p>
        <% (post.comments).each do |comment| %>
        <div id="comment">
          <%= comment.text %> <div id="byline"><%=comment.user.username %></div><p id="time"><%= comment.date %> </p> <p id="time"> <%= comment.time %></p>
        </div>
        <% end %>
        <%= link_to "<span class='glyphicon glyphicon-plus' aria-hidden='true'></span>".html_safe, post_path(post) %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <% if @counter == 0 %>
      <% @tags.each do |tag| %>
        <%= link_to "##{tag.tagtext}", tag_path(tag) %>
      <% end %>
      <% @counter = 1 %>
    <% end %>
  </div>
</div>
<% end %>

app/views/posts/new.html.erb
<%= form_for [@post], :html => {:class => "form-horizontal"} do |f| %>
  <div class="form-group">
    <label class="col-sm-2 control-label"></label>
    <div class="col-sm-8">
      <%= f.text_field :title, placeholder: "title", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label"></label>
    <div class="col-sm-8">
      <%= f.text_area :text, placeholder: "post", class: "form-control", :cols => "10", :rows => "10" %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label"></label>
    <div class="col-sm-4">
      <input class="form-control" type="text" name="tagtext" placeholder="tag" />
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "create", class: "btn btn-default btn-primary"  %>
    </div>
  </div>
<% end  %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 style="display:inline" class="panel-title"><%= @post.title %></h3>
        <% if @user.id == @post.user.id %>
          <%= link_to "<span id='glyph' class='glyphicon glyphicon-trash' aria-hidden='true'></span>".html_safe, post_path(@post), method: :delete %>
          <%= link_to "<span id='glyph' class='glyphicon glyphicon-edit' aria-hidden='true'></span>".html_safe, edit_post_path(@post) %>
        <% end %>
      </div>
      <div class="panel-body">
        <p><%= @post.text %></p>
        <div id="byline"><%= @post.user.username %></div><div id="time"><%= @post.date %> </div> <div id="time"> <%= @post.time %></div>
        <h6><% (@post.tags).each do |tag| %><span> <%= link_to "##{tag.tagtext}", tag_path(tag) %></span><% end %></h6>
      </div>

      <div class="well">
        <p>comments</p>
        <% (@post.comments).each do |comment| %>
        <div id="comment">
          <%= comment.text %> <div id="byline"><%=comment.user.username %></div><p id="time"><%= comment.date %> </p> <p id="time"> <%= comment.time %></p>
        </div>
        <% end %>
      </div>
    </div>

    <%= form_for [@post, @comment], :html => {:class => "form-horizontal"} do |f| %>
      <div class="form-group">
        <label class="control-label"></label>
        <div class="col-md-12">
          <%= f.text_field :text, class: "form-control", placeholder: "comment" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-2">
            <%= f.submit "create", class: "btn btn-default btn-primary"  %>
        </div>
      </div>
    <% end  %>

app/views/tags/show.html.erb
<% @counter = 0 %>
<% @posts.each do |post| %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
    <% if @counter == 0 %>  <h4 style="margin-bottom: 15px;">#<%= @tag.tagtext %></h4> <% @counter = 1 %> <% end %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= link_to "#{post.title}", post_path(post) %></h3>
        </div>
        <div class="panel-body">
          <p><%= post.text %></p>
          <p id="byline"> by <%= post.user.username %></p>
          <h6><% (post.tags).each do |tag| %><span> <%= link_to "##{tag.tagtext}", tag_path(tag) %></span><% end %></h6>
        </div>

        <div class="well">
          <p>comments</p>
          <% (post.comments).each do |comment| %>
          <div id="comment">
            <%= comment.text %> <div id="byline"><%=comment.user.username %></div>
          </div>
          <% end %>
        </div>

      </div>
    </div>
  <div class="col-md-4"></div>
</div>
<% end %>

app/views/users/show.html.erb
<div id="alert" class="alert alert-info" role="alert"><%= flash[:notice]%></div>
<% @counter = 0 %>
<% @posts.each do |post| %>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-5">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= link_to "#{post.title}", post_path(post) %></h3>
      </div>
      <div class="panel-body">
        <p><%= post.text %></p>
        <div id="byline"><%= post.user.username %></div><div id="time"><%= post.date %> </div> <div id="time"> <%= post.time %></div>
        <h6><% (post.tags).each do |tag| %><span> <%= link_to "##{tag.tagtext}", tag_path(tag) %></span><% end %></h6>
      </div>

      <div class="well">
        <p>comments</p>
        <% (post.comments).each do |comment| %>
        <div id="comment">
          <%= comment.text %> <div id="byline"><%=comment.user.username %></div><p id="time"><%= comment.date %> </p> <p id="time"> <%= comment.time %></p>
        </div>
        <% end %>
        <%= link_to "<span class='glyphicon glyphicon-plus' aria-hidden='true'></span>".html_safe, post_path(post) %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
  </div>
</div>
<% end %>

app/views/users/sign_in.html.erb
<%= flash[:notice]%>
<%= form_tag("/sign_in", method: "post") do %>

    <div class="col-md-8">
      <input style="margin: 10px" class="form-control" type="text" name="username" placeholder="username" />
    </div>

    <div class="col-md-8">
      <input style="margin: 10px" class="form-control" type="password" name="password" placeholder="password" />
    </div>

    <div class="col-md-8">
      <input style="margin: 10px" class="btn btn-default btn-primary" type="submit" value="sign in" />
    </div>

<% end %>

app/views/users/sign_up.html.erb
<%= flash[:notice]%>
<%= form_tag("/sign_up", method: "post") do %>

    <div class="col-md-8">
      <input style="margin: 10px" class="form-control" type="text" name="username" placeholder="username" />
    </div>

    <div class="col-md-8">
      <input style="margin: 10px" class="form-control" type="password" name="password" placeholder="password" />
    </div>

    <div class="col-md-8">
      <input style="margin: 10px" class="form-control" type="password" name="password_confirmation" placeholder="confirm" />
    </div>

    <div class="col-md-8">
      <input style="margin: 10px" class="btn btn-default btn-primary" type="submit" value="sign up" />
    </div>
<% end %>